#### コラム: 日付・時間の書式

文字列を任意の書式で出力する`format()`や`strftime()`などの関数には共通した書式が適用される(表XX)。同様に`strptime()`では引数に与えた日付・時間を表現する書式を指定することで、日付・時間のオブジェクトを生成する。

<!-- 大文字と小文字の区別 -->

<!-- 表番号 2015年12月25日 14時１分30秒 を例にした -->

| 表記 | 表現         | 表記の例       |
|------|--------------|----------------|
| %a   | 曜日名の略称 | Fri    |
| %A   | 完全な曜日名 | Friday |
| %b   | 月名の略称   | Dec    |
| %B   | 完全な月名   | December |
| %c   | 日付と時間 ("%a %b %e %H:%M:%S %Y")   | Fri Dec 25 14:00:00 2015 |
| %y   | 西暦の下２桁 | 15 |
| %Y   | 西暦         | 2015 |
| %m   | 月           | 12 |
| %d   | 日(１月の範囲) | 25 |
| %j   | 日(１年の範囲) | 359 |
| %H   | 時間(24時間) | 14 |
| %I   | 時間(12時間) | 02 |
| %M   | 分             | 01 |
| %p   | 午前と午後の区分 | PM |
| %S   | 秒             | 30 |
| %w   | 曜日\footnote{日曜日を０とする} | 5 |
| %x   | 年月日 ("%m/%d/%y") | 12/25/2015 |
| %X   | 時刻 ("%H:%M:%S")   | 14:01:30 |

```{r}
# 書式を指定して日付・時間クラスオブジェクトの表現を変更する
# これらはすべて文字列クラスオブジェクトに変換される点に注意する
Sys.Date()
format(Sys.Date(), "%Y年%m月%d日")
format(Sys.time(), "%x %X")
```

```{r}
# 文字列から書式を指定した日付・時間オブジェクトを作成
strptime("2017年2月25日 14:01:30", format = "%Y年%m月%d日 %X")
```
